### ISSUE TITLE
merge policies dont seem to like MsigPending query...

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#101]
It's so odd - i can't tell why this would work for MessagesConfirmed, but not for MsigPending. https://github.com/glifio/react-components/commit/4f19b7bef8392bc52d69af3fd69da3c3deb16469

The result is:

![image](https://user-images.githubusercontent.com/12353734/151077919-a449ee4c-0081-4643-92be-c408f7cba4c4.png)

Even when i throw a log in the `merge` function, it never gets called?

**Comment by navFooh** [comment]
Fixed in linked PR
