### ISSUE TITLE
figure out how to get package version in the logger, or just make those optional

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#139]
When we actually `import packagejson from '../package.json'` into the `logger` file, this breaks the typescript build...

**Comment by navFooh** [comment]
Is this still the case? It seems like the TypeScript builds are fine?

**Comment by navFooh** [comment]
Fixed using `NEXT_PUBLIC_PACKAGE_NAME` and `NEXT_PUBLIC_PACKAGE_VERSION` in `next.config.js`
