### ISSUE TITLE
App error pages are not using correct layout

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#205]
I think the error pages should just look nice, and probably show the AppHeader with the top left app link showing (no top right links).

I've seen the error pages look the same on the explorer, wallet, and safe, think they just need the new layout stuff?

**Comment by Schwartz10** [comment]
Example - https://github.com/glifio/explorer/issues/28

**Comment by Schwartz10** [comment]
On error pages, i think it makes sense to show the app header, links depending on context but _at least_ the app specific glif / home icon on the top left

**Comment by navFooh** [comment]
Linked it to the PR for `react-components`, but will actually be fixed by the PRs for the apps
