### ISSUE TITLE
App header flashes at bottom of screen on page load

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#213]
Try navigating directly to this link - see how it shows the appheader before rerouting to the landing page?

https://wallet-calibration.glif.link/home

**Comment by navFooh** [comment]
I'm having trouble to reproduce this, even when disabling cache and throttling the connection, I see the landing page straight away. Before the landing page loads, I just see a white screen

**Comment by Schwartz10** [comment]
@navFooh maybe try logging in to the wallet, and then refresh the page?

**Comment by navFooh** [comment]
Right, yeah now I can reproduce, think I have an idea
