### ISSUE TITLE
ErrorView component should include link to Discord and/or Twitter

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#220]
@navFooh i think its still nice to put a link to our Twitter and/or discord in the ErrorView component.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/12353734/158421655-88c497bf-ba0e-4947-b080-b02360693b2d.png">

<img width="533" alt="image" src="https://user-images.githubusercontent.com/12353734/158421883-66602606-452a-4dc3-b294-6755c251d82b.png">

This is what it currently looks like when you pass `linkhref` and `linkdisplay`

I think we should remove these as props, and display (at least) the Discord link somewhere on the error view

**Comment by navFooh** [comment]
The `linkhref` and `linkDisplay` props should probably stay since in some cases they are used to provide a specific link for the error, for example: https://safe-calibration.glif.link/error/use-chrome

That is also consistent with the Warning component.

I'll propose an update in a new PR.
