### ISSUE TITLE
FilecoinNumber + Number input breaks on `.` + `0` input

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#316]
Try typing `.0001` into the input (starting with the decimal), it reverts to 0001 (no decimal)

**Comment by navFooh** [comment]
That doesn't sound unexpected to me. BigInts are whole numbers (integers) so they don't support fractions. That kind of limits their use, but can still be convenient when you need to represent integers larger than Number.MAX_SAFE_INTEGER

**Comment by navFooh** [comment]
When I look in the Filecoin spec, I actually see that there's a few values in a block that are (u)int64 or BigInt as well. There I think this could potentially be better to use the BigInt input instead of Number, if we ever want users to enter them manually

**Comment by Schwartz10** [comment]
Hey @navFooh I tested this and it actually does not occur on BigInt input, but it does occur on FilecoinNumber and Number inputs. The problem occurs because `".0"` converts into `"0'` when we cast the new input value into `FilecoinNumber` and `Number` types. This happens in the `onChangeBase` functions. It oddly doesn't occur when prepending decimals with `0`, like `0.001`.

We obviously need to be very precise here in avoiding unexpected behavior because these are used by the wallet and safe. What do you think is the best approach to solving this issue? I tried manually casting `.0__` into `0.0___` and that didn't work either ?? . Should we just go with text inputs for the FilecoinNumber input?

**Comment by navFooh** [comment]
I see, this is indeed a problem, good catch!

Let me try one more thing tomorrow morning. I like the number input because it prevents entering non-numerical characters and if we open it up to mobile, it also triggers the numerical virtual keyboard.

**Comment by Schwartz10** [comment]
I like `type="number"` inputs for this use case too because it also provides good UX around using the arrow keys + `step` props to control the input value. Looking forward to seeing what you come up with here @navFooh. I'm surprised i haven't seen more written about this online - feels like it would be a more common problem
