### ISSUE TITLE
Empty params displays "false" on msg detail

### ISSUE THREAD

**Issue by Schwartz10** [glifio/react-components#455]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/12353734/177247786-06c2f696-4497-4317-b84c-6c08320bd21e.png">

If params are empty, it should just be an empty string

**Comment by navFooh** [comment]
This happened when params was `null`, will now render like this:

![image](https://user-images.githubusercontent.com/394452/177368214-80074c4f-a44b-4e56-9221-ed9ec95423c0.png)

Let me know if that works!
