### ISSUE TITLE
Remove missing data WarningBox and make a smaller, nicer less conspicuous warning instead

### ISSUE THREAD

**Issue by navFooh** [glifio/react-components#461]
Just making an issue for this so we don't forget.

The `daysLeft` indication at the following text will start counting back up after `FINISH_DATE` has passed:

```
Some transactions are currently missing for the next {daysLeft}{' '}
while our servers finish syncing with Filecoin Mainnet.
```

**Comment by Schwartz10** [comment]
Changing this ticket since it's obsolete anyways
